//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUENTAS_POR_PAGAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURASOMAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURASOMAR()
        {
            this.CHEQUESOMAR = new HashSet<CHEQUESOMAR>();
        }
    
        public int NUMEROFACTURA { get; set; }
        public string CODIGO { get; set; }
        public Nullable<decimal> VALORFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUESOMAR> CHEQUESOMAR { get; set; }
        public virtual PROVEEDORESOMAR PROVEEDORESOMAR { get; set; }
    }
}
